version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.6.2
    container_name: elasticsearch
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elk

  kib:
    image: kibana:7.6.2
    container_name: kib
    ports:
      - 5601:5601
    networks:
      - elk

  logstash:
    image: logstash:7.6.2
    command: bash -c "logstash -f /usr/share/logstash/pipeline/logstash.conf"
    container_name: logstash
    ports:
      - 9600:9600
      - 1903:1903
    networks:
      - elk
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml
    depends_on: ['elasticsearch']
    healthcheck:
      test: bin/logstash -t
      interval: 60s
      timeout: 50s
      retries: 5


volumes:
  data01:
    driver: local

networks:
  elk:
    driver: bridge 